### ISSUE TITLE
battery stats

### ISSUE THREAD

**Issue by travisghansen** [eschava/psmqtt#13]
Cool project. Would it be possible to add battery stats as well?

Specific use-case for me is to send to mqtt to be received by `Node-RED` to turn around and control a z-wave power outlet so I can sanely condition a brand new battery for my laptop (turn on power once battery is at or below X percent and turn it off once battery is at or above Y percent).

**Comment by eschava** [comment]
Done
Use sensors_battery/percent topic

**Comment by travisghansen** [comment]
Very cool! All looks well at the moment but you may want to check the time left data point. Here is what it looks like in json format:

```
{"percent": 100.0, "secsleft": -2, "power_plugged": true}
```

And topic format produces:

```
BatteryTime.POWER_TIME_UNLIMITED
```

I suspect the later isn't getting rendered properly for some reason?

**Comment by travisghansen** [comment]
I should say that's what I get when plugged in...when unplugged a valid value is sent for both styles.

**Comment by eschava** [comment]
Thanks, should be fixed now
Also updated docs for -1/-2 special values of secsleft

**Comment by travisghansen** [comment]
Looks great! Thanks for the help!
