### ISSUE TITLE
reading Temperature on raspi3 fails

### ISSUE THREAD

**Issue by webcharlyx** [eschava/psmqtt#15]
hey eschava!
First of all: Thanks for this great tool and all the effort you had!
Using current code on raspberry3B it fails on reading the Temperature (please see attached files)
testing with psutil itself the current temperature is available.
do you think, it would be possible to fix/add?
[psutil.raspberry3B.txt](https://github.com/eschava/psmqtt/files/4470159/psutil.raspberry3B.txt)
[tests.py.raspberry3B.txt](https://github.com/eschava/psmqtt/files/4470160/tests.py.raspberry3B.txt)

**Comment by eschava** [comment]
Thanks for the report!
Seems to be fixed now

**Comment by webcharlyx** [comment]
Well done, thanks.
seems to work now perfectly.
[new.tests.py.raspberry3B.txt](https://github.com/eschava/psmqtt/files/4482429/new.tests.py.raspberry3B.txt)

**Comment by webcharlyx** [comment]
#9
