### ISSUE TITLE
View sensors in HA

### ISSUE THREAD

**Issue by divemasterjm** [eschava/psmqtt#17]
I have your program running, i can see it in mosquito broker but im unable to see it in homeassistant, can u please help me?

**Comment by divemasterjm** [comment]
i manage to view it manually adding, but ive got an error with temprature sensors in mac mini

**Comment by eschava** [comment]
what's the error?

**Comment by divemasterjm** [comment]
schedule = {
    "every 1 minute" :    [
        "cpu_percent",
        "virtual_memory/percent",
        "sensors_temperatures/*",
     ],

**Comment by divemasterjm** [comment]
ERROR:root:sensors_temperatures/*: module 'psutil' has no attribute 'sensors_temperatures'
Traceback (most recent call last):
  File "/Users/juanma/psmqtt/psmqtt.py", line 56, in run_task
    payload = get_value(task)
  File "/Users/juanma/psmqtt/psmqtt.py", line 81, in get_value
    value = handlers[head].handle(tail)
  File "/Users/juanma/psmqtt/handlers.py", line 283, in handle
    tup = self.get_value()
  File "/Users/juanma/psmqtt/handlers.py", line 311, in get_value
    return psutil.sensors_temperatures()
AttributeError: module 'psutil' has no attribute 'sensors_temperatures'
ERROR:root:sensors_temperatures/*: module 'psutil' has no attribute 'sensors_temperatures'
Traceback (most recent call last):
  File "/Users/juanma/psmqtt/psmqtt.py", line 56, in run_task
    payload = get_value(task)
  File "/Users/juanma/psmqtt/psmqtt.py", line 81, in get_value
    value = handlers[head].handle(tail)
  File "/Users/juanma/psmqtt/handlers.py", line 283, in handle
    tup = self.get_value()
  File "/Users/juanma/psmqtt/handlers.py", line 311, in get_value
    return psutil.sensors_temperatures()
AttributeError: module 'psutil' has no attribute 'sensors_temperatures'

**Comment by divemasterjm** [comment]
what  a pity, thanks for your help

**Comment by exeljb** [comment]
I know this is old and closed but I wanted to mention that there's an open source project called Fanny that's able to display CPU temps and fan speed.  I'm curious how possible it would be to implement whatever method that project uses to get compatibility with this one. 

The repo is at.... https://github.com/DanielStormApps/Fanny/

It would be great if i could get this on my mac mini that's running my home assistant instance.
