### ISSUE TITLE
Docker?

### ISSUE THREAD

**Issue by fabiosoft** [eschava/psmqtt#19]
Any plans to support DockerFile container?

What volumes/folders does it need? Some root privilegies?
On my NAS i have all containerized and i'd like to have this too.

**Comment by eschava** [comment]
I do not use Docker but adapted Dockerfile from my other project
You can try it

**Comment by fabiosoft** [comment]
Thanks, i will try locally and the deploy to my NAS. 
First I need to find out how map the conf file to a volume to make it customizable

**Comment by Tiago90GH** [comment]
@fabiosoft if you manage to get it working with docker can you share please ? im trying to do the same

**Comment by johanko** [comment]
More than 2 years late, but I needed this and created this docker image:
https://hub.docker.com/r/nublet/ps2mqtt

**Comment by f18m** [comment]
hi @johanko,
I'm interested in the docker image as well... why don't you open a PR to this repo with your tested changes on the Dockerfile to make them more visible? thanks!

**Comment by f18m** [comment]
I think this ticket can now be closed given that now the project uses an automatic github CI to publish docker images so everybody can simply consume the software with a 'docker run'. Check the README. Closing this ticket.
