### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by zpfvo** [eschava/psmqtt#2]
Hi!
I would like to contribute to this project and i also like to use it in a project i am currently working on.
Would mind licensing this project? Maybe MIT? http://choosealicense.com

Regards and keep up the good work :)

**Comment by eschava** [comment]
Hi,
Thanks for your attention to my project!

Yes, MIT should work
Are there any steps to specify what license is used by project?

**Comment by zpfvo** [comment]
Hi,
Just create a file named 'LICENSE' with the license text. Example: https://github.com/kipe/enocean
Thank you!

**Comment by eschava** [comment]
Added, thank you!
