### ISSUE TITLE
Run as Service or daemon at start up

### ISSUE THREAD

**Issue by shaneaj** [eschava/psmqtt#4]
Sorry if this isn't the right method to ask this question. I want to use your script to report the status of my raspberry pi's starting automatically at boot.

However I run in problems because I think the script expects it to be launched from the psmqtt directory only.

When i try to use "python /home/psmqtt/psmqtt.py" to start the script I get an error message;

"Cannot load configuration from file psmqtt.conf: [Errno 2] No such file or directory: 'psmqtt.conf'"

I was hoping to use cron job to start the script at boot do you think that is the best way or should be via a service on boot [http://blog.scphillips.com/posts/2013/07/getting-a-python-script-to-run-in-the-background-as-a-service-on-boot/](url) for example.

I'm a bit of a noob and not really sure what it is I'm doing. Appreciate your help and thanks for the great script it does so much so easily.

BTW  - Is there a task for reporting the CPU temperature? I had a look but couldn't see anything.

Regards

Shane

**Comment by eschava** [comment]
Hi, it's okay to ask questions here but next time you can use my gmail email with the same eschava user name

To start psmqtt on startup from /etc/rc.local I use next command
PSMQTTCONFIG=/home/cubie/psmqtt/psmqtt.conf /home/cubie/psmqtt/psmqtt.py &
You can adjust it with your pathes

CPU temp parameter is not providen by parent psutil library so it is not available in psmqtt as well
Afaik they discussed such parameter (you can find appropriate github issue) but are not going to implement it at the nearest time
You can setup cron task executing some command to get cpu temp and publish it using mosquitto_sub command

**Comment by gungstarbeiter** [comment]
If someone trying to run **psmqtt** with **systemd**, service file should look as this:
```
[Unit]
Description=psmqtt service
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=10
User=root
Environment="PSMQTTCONFIG=/opt/psmqtt/psmqtt.conf"
ExecStart=/usr/bin/python3 /opt/psmqtt/psmqtt.py

[Install]
WantedBy=multi-user.target
```
