### ISSUE TITLE
Autostart psmqtt

### ISSUE THREAD

**Issue by mario-g0** [eschava/psmqtt#8]
I finally managed to install on macOS, is there a way to start the program on boot?  if I close the terminal, will the program keep running?
also, what's the correct syntax to get cpu temp for macOS? sensor_temperatures doesn't seem to work (I get an error)

**Comment by eschava** [comment]
To autostart program you can try with the solution suggested here:
https://superuser.com/questions/229773/run-command-on-startup-login-mac-os-x

CPU temp for MacOS is not implemented yet:
https://github.com/giampaolo/psutil/issues/1134
